FROM tomcat:8-jre8

# Create app directory
WORKDIR $CATALINA_HOME/bin
COPY jaas.config $CATALINA_HOME/conf
COPY context.xml $CATALINA_HOME/conf
COPY server.xml $CATALINA_HOME/conf
CMD ["catalina.sh", "run"]

EXPOSE 8080